name: Data Guard
version: 2.4.0
description: Data Guard plugin protects your website from the content copying.
icon:
  name: shield-alt
  set: fontawesome|solid
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/data-guard
bugs: https://github.com/flextype-plugins/data-guard/issues
license: MIT
